#!/bin/sh

find tests -name '*.java' | xargs rm 2>/dev/null || echo "No scenes to remove"
find feynstein -name '*.class' | xargs rm 2>/dev/null || echo "No classfiles to remove"
find feynstein -name '*~' | xargs rm 2>/dev/null || echo "No backup files to remove"
